name: Sklearn Server Docker Publisher

on:
  push:
    branches:
      - master
      - sklearn-runtime-schedule-retry-on-failure
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: sklearnserver

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Main Test job
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64/v8, linux/ppc64le]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/cache
            ~/.cache/pypoetry/artifacts
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Run tests
        id: run_tests  # Give this step an ID to reference its result
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}
          context: python
          file: python/sklearn.Dockerfile
          push: false
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          provenance: false

    timeout-minutes: 10 # Time limit for each job

  # Retry job that executes if the test job fails or is canceled for linux/ppc64le
  retry:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() }}  # Always run this job after test
    strategy:
      matrix:
        platform: [linux/ppc64le]  # Only retry for linux/ppc64le
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/cache
            ~/.cache/pypoetry/artifacts
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Run tests again
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ matrix.platform }}
          context: python
          file: python/sklearn.Dockerfile
          push: false
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          provenance: false

  # Log the test result (always executes)
  log-result:
    runs-on: ubuntu-latest
    needs: [test, retry]
    if: ${{ always() }}  # Always execute this job
    steps:
      - name: Log test result
        run: |
          echo "Test job result: ${{ needs.test.result }}"
          echo "Retry job result: ${{ needs.retry.result }}"


